services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somethingrandomjustforittowork
      MYSQL_DATABASE: blogic_crm
      MYSQL_USER: blogic_user
      MYSQL_PASSWORD: hello1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "ConnectionStrings__DefaultConnection=Server=mysql;database=blogic_crm;User=blogic_user;Password=hello1234;"
    depends_on:
      mysql:
        condition: service_healthy
      
      

