// <auto-generated />
using System;
using BlogicCRM.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogicCRM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608204339_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1985, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Barry_Moran561@jcf8v.mobi",
                            FirstName = "Jan",
                            LastName = "Novák",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1986, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ema_Mcleod5369@yahoo.directory",
                            FirstName = "David",
                            LastName = "Svoboda",
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1987, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maxwell_Ebbs6093@1kmd3.press",
                            FirstName = "Petr",
                            LastName = "Novotný",
                            Phone = "555123456"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1988, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Louise_Khan3677@ds59r.host",
                            FirstName = "Martin",
                            LastName = "Dvořák",
                            Phone = "444987654"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1989, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Aileen_Gaynor5441@hepmv.meet",
                            FirstName = "Tomáš",
                            LastName = "Černý",
                            Phone = "333555123"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1990, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sloane_Tanner4692@kyb7t.info",
                            FirstName = "Lukáš",
                            LastName = "Procházka",
                            Phone = "222444987"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1991, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adalind_Lindsay1835@yfxpw.edu",
                            FirstName = "Michal",
                            LastName = "Kovář",
                            Phone = "111333555"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1992, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maria_Potts856@v1wn5.zone",
                            FirstName = "Jakub",
                            LastName = "Veselý",
                            Phone = "666777888"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1993, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mason_Tutton6832@xtwt3.online",
                            FirstName = "Filip",
                            LastName = "Horák",
                            Phone = "999000111"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1994, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Fiona_Saunders8101@karnv.software",
                            FirstName = "Vojtěch",
                            LastName = "Němec",
                            Phone = "888999000"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consultants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1985, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sebastian_Sanchez2407@yvu30.website",
                            FirstName = "Jaroslav",
                            LastName = "Fiala",
                            Phone = "111888777"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1986, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Josh_Logan4466@uagvw.app",
                            FirstName = "Josef",
                            LastName = "Král",
                            Phone = "222999888"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1987, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Roger_Bingham7598@dvqq2.meet",
                            FirstName = "Adam",
                            LastName = "Richter",
                            Phone = "333111000"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1988, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bryon_Windsor6229@iscmr.meet",
                            FirstName = "Matěj",
                            LastName = "Beneš",
                            Phone = "444222111"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1989, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Courtney_Salt2851@y96lx.mobi",
                            FirstName = "Daniel",
                            LastName = "Růžička",
                            Phone = "555444333"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1990, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rocco_Richards6731@bcfhs.business",
                            FirstName = "Ondřej",
                            LastName = "Pokorný",
                            Phone = "777666555"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1991, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Fiona_Saunders8101@karnv.software",
                            FirstName = "Vojtěch",
                            LastName = "Němec",
                            Phone = "888999000"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1992, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mason_Tutton6832@xtwt3.online",
                            FirstName = "Filip",
                            LastName = "Horák",
                            Phone = "999000111"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1993, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Maria_Potts856@v1wn5.zone",
                            FirstName = "Jakub",
                            LastName = "Veselý",
                            Phone = "666777888"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            BirthNumber = "1234567890",
                            Birthdate = new DateTime(1994, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Adalind_Lindsay1835@yfxpw.edu",
                            FirstName = "Michal",
                            LastName = "Kovář",
                            Phone = "111333555"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Closed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Effective")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClientId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Closed = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Closed = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Closed = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Closed = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Closed = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Closed = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000007"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Closed = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Closed = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Closed = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Closed = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Closed = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Closed = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Closed = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000007"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Closed = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Closed = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Closed = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Closed = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Closed = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Closed = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Closed = new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Effective = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ČSOB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AEGON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AXA"
                        });
                });

            modelBuilder.Entity("ContractConsultant", b =>
                {
                    b.Property<Guid>("ConsultantsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipatingContractsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConsultantsId", "ParticipatingContractsId");

                    b.HasIndex("ParticipatingContractsId");

                    b.ToTable("ContractConsultant");
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.HasOne("BlogicCRM.Models.Consultant", "Admin")
                        .WithMany("AdministeredContracts")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Institution", "Institution")
                        .WithMany("Contracts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ContractConsultant", b =>
                {
                    b.HasOne("BlogicCRM.Models.Consultant", null)
                        .WithMany()
                        .HasForeignKey("ConsultantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ParticipatingContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Consultant", b =>
                {
                    b.Navigation("AdministeredContracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
