// <auto-generated />
using System;
using BlogicCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogicCRM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250606070135_AddConsultantDbSet")]
    partial class AddConsultantDbSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(1996, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "novak@mail.cz",
                            FirstName = "Jan",
                            LastName = "Novák",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(2002, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david@gmail.com",
                            FirstName = "David",
                            LastName = "Marek",
                            Phone = "123456789"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consultants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(1998, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "juank@mail.cz",
                            FirstName = "Juan",
                            LastName = "Fernandez",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(2000, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jose@gmail.com",
                            FirstName = "Jose",
                            LastName = "Gomez",
                            Phone = "123456789"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Closed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Effective")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClientId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Closed = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Effective = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Closed = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Effective = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ČSOB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AEGON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AXA"
                        });
                });

            modelBuilder.Entity("ContractConsultant", b =>
                {
                    b.Property<Guid>("ConsultantsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipatingContractsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConsultantsId", "ParticipatingContractsId");

                    b.HasIndex("ParticipatingContractsId");

                    b.ToTable("ContractConsultant");
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.HasOne("BlogicCRM.Models.Consultant", "Admin")
                        .WithMany("AdministeredContracts")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Institution", "Institution")
                        .WithMany("Contracts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ContractConsultant", b =>
                {
                    b.HasOne("BlogicCRM.Models.Consultant", null)
                        .WithMany()
                        .HasForeignKey("ConsultantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ParticipatingContractsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Consultant", b =>
                {
                    b.Navigation("AdministeredContracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
