// <auto-generated />
using System;
using BlogicCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogicCRM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605141359_FixContract")]
    partial class FixContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(1996, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "novak@mail.cz",
                            FirstName = "Jan",
                            LastName = "Novák",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BirthNumber = "123456/7890",
                            Birthday = new DateTime(2002, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david@gmail.com",
                            FirstName = "David",
                            LastName = "Marek",
                            Phone = "123456789"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Closed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Effective")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e0b5eeb-8202-475f-a9d3-4e6b3074fc1f"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Closed = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Effective = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 1
                        },
                        new
                        {
                            Id = new Guid("27d4984c-5920-4394-b99e-b656bd4eafb9"),
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Closed = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Created = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Effective = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            InstitutionId = 2
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ČSOB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AEGON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AXA"
                        });
                });

            modelBuilder.Entity("BlogicCRM.Models.Contract", b =>
                {
                    b.HasOne("BlogicCRM.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogicCRM.Models.Institution", "Institution")
                        .WithMany("Contracts")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("BlogicCRM.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BlogicCRM.Models.Institution", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
